spring.application.name=ms-security
server.port=8080
app.storage.location=uploads/photos
app.base.url=http://localhost:8080

spring.mongodb.uri=mongodb+srv://jacobo:HIXZaz8I8zqVXvCO@cluster0.bvciedz.mongodb.net/?appName=Cluster0

spring.mongodb.database=db_security

captcha.key = 6LcykpEsAAAAAPjZvWcWcLrrXAU-9t9dlh87a2Ec

jwt.secret=aaa
jwt.expiration=3600000
rest.expiration =360000

notifications.url=http://127.0.0.1:5000